services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=chess
      - POSTGRES_PASSWORD=chess_pass
      - POSTGRES_DB=chess_trainer_db
    ports:
      - "5432:5432"
    volumes:
      - chess_pgdata:/var/lib/postgresql/data

volumes:
  chess_pgdata:
