"""Generate 07_0_mental_model_lab.ipynb — test human 1600 mental model from PGN file."""

import json
from pathlib import Path

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Module 7.0 — Laboratorio modelo mental 1600 (rapid)\n",
            "\n",
            "**Fuentes:**\n",
            "- Diagramas HTML: [`07_cc_detection_algoritms/`](./07_cc_detection_algoritms/)\n",
            "- Informe de coherencia vs 07\\*: [`07_cc_human_mental_model_analysis.md`](./07_cc_human_mental_model_analysis.md)\n",
            "- Código: `analysis/mental_model/` (implementación *derivada* del HTML; la spec canónica humana sigue siendo el HTML)\n",
            "\n",
            "**Objetivo:** cargar una partida (PGN o `game_id` de SQLite), elegir una jugada, y recorrer paso a paso:\n",
            "1. ¿Modo rápido o crítico?\n",
            "2. Disparadores E1–E11\n",
            "3. Plan de pensamiento (G, D, S)\n",
            "4. Mapeo a razones 07-base\n",
            "5. (Opcional) clasificar una candidata UCI + anti-blunder\n",
            "\n",
            "**No requiere** LLM ni Stockfish en este notebook.\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 0 — Configuración\n",
            "\n",
            "Carga de partida (F07-001):\n",
            "1. Copiá tus `.pgn` a `data/games/` (esta carpeta del curso).\n",
            "2. Elegí el archivo con **`PGN_PATH`** (por defecto `f07_002_white.pgn`).\n",
            "3. Opcional: **`GAME_ID`** de `course_data.sqlite` (curso). No usa PostgreSQL.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "# F07-001 bootstrap v2 — does not use src/analysis\n",
            "from pathlib import Path\n",
            "import json\n",
            "import sys\n",
            "\n",
            "_cwd = Path.cwd().resolve()\n",
            "for _candidate in (_cwd, _cwd / 'docs' / 'ai_chess_coach_course'):\n",
            "    if (_candidate / 'mm_lab_imports.py').is_file():\n",
            "        sys.path.insert(0, str(_candidate))\n",
            "        break\n",
            "\n",
            "import chess\n",
            "import pandas as pd\n",
            "import os\n",
            "from mm_lab_imports import prepare_sys_path, load_repo_dotenv, repo_root\n",
            "\n",
            "COURSE_ROOT = prepare_sys_path()\n",
            "env_file = load_repo_dotenv(COURSE_ROOT, override=True)\n",
            "from analysis.position_extractor import (\n",
            "    import_game_from_file,\n",
            "    load_game_from_db,\n",
            ")\n",
            "from analysis.game_models import select_analyzed_player\n",
            "from analysis.interactive_board import show_interactive_board\n",
            "from analysis.engine_eval import analyze_ply_for_player, ply_evaluation_loss, stockfish_available\n",
            "from analysis.multipv import analyze_multipv, evaluate_played_move\n",
            "from analysis.comparison import compare_played_to_candidates\n",
            "from analysis.abstention import assess_diagnosis_abstention\n",
            "from analysis.review_pack import build_review_pack, default_review_pack_name, write_review_pack\n",
            "from analysis.notation import uci_to_san, san_to_uci\n",
            "from analysis.engine_triggers import ply_evaluation_drop, only_move_trigger\n",
            "from analysis.criticality import assess_ply_criticality, rank_player_game\n",
            "from analysis.mental_model import assess_decision_point\n",
            "from analysis.mental_model.flow import assess_move_before_play\n",
            "from analysis.mental_model.candidate_taxonomy import sort_candidates_by_priority\n",
            "\n",
            "ARTIFACT_DIR = COURSE_ROOT / 'artifacts' / 'module07'\n",
            "ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)\n",
            "GAMES_DIR = COURSE_ROOT / 'data' / 'games'\n",
            "GAMES_DIR.mkdir(parents=True, exist_ok=True)\n",
            "print('Course analysis:', (COURSE_ROOT / 'analysis' / 'position_extractor.py'))\n",
            "print('Carpeta PGN:', GAMES_DIR)\n",
            "pgn_files = sorted(GAMES_DIR.glob('*.pgn'))\n",
            "if pgn_files:\n",
            "    print('Archivos .pgn:')\n",
            "    for _pgn in pgn_files:\n",
            "        print(' -', _pgn.name)\n",
            "else:\n",
            "    print('No hay .pgn. Copiá partidas a esa carpeta.')\n",
            "\n",
            "# --- Editar aquí ---\n",
            "GAME_ID = ''   # game_id de course_data.sqlite; vacío = archivo PGN\n",
            "PGN_PATH = GAMES_DIR / 'f07_002_white.pgn'  # o f07_002_black.pgn / tu archivo\n",
            "PLAYER_NAME = 'cmess1315'\n",
            "PLAYER_COLOR = None   # None | 'white' | 'black' (desambiguar o forzar lado)\n",
            "PLAYER_ELO = 1600\n",
            "TIME_CONTROL = 'rapid'   # bullet | blitz | rapid | classical\n",
            "CANDIDATE_UCI = None   # ej. 'e2e4'; None = primera candidata heurística\n",
            "\n",
            "print('Course root:', COURSE_ROOT)\n",
            "print('Repo root:', repo_root(COURSE_ROOT))\n",
            "print('.env file:', env_file or (repo_root(COURSE_ROOT) / '.env'))\n",
            "print('GAME_ID source: course_data.sqlite (not PostgreSQL)')\n",
            "print('course_data.sqlite exists:', (COURSE_ROOT / 'course_data.sqlite').is_file())\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 1 — Cargar partida (F07-001)\n",
            "\n",
            "Paso 1b (F07-002): `select_analyzed_player` deja solo las jugadas del jugador analizado.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "if GAME_ID and str(GAME_ID).strip():\n",
            "    normalized_game = load_game_from_db(str(GAME_ID).strip())\n",
            "else:\n",
            "    normalized_game = import_game_from_file(PGN_PATH)\n",
            "\n",
            "headers = normalized_game.headers\n",
            "white = normalized_game.white_player or '?'\n",
            "black = normalized_game.black_player or '?'\n",
            "result = normalized_game.result or '*'\n",
            "sans = [p.san for p in normalized_game.plies]\n",
            "\n",
            "print(f'Fuente: {normalized_game.source} | game_id: {normalized_game.game_id}')\n",
            "print(f'White: {white}  Black: {black}  Result: {result}')\n",
            "print(f'Jugadas en la línea principal: {len(normalized_game.plies)}')\n",
            "print('Primeras plies:', ' '.join(sans[:8]), '...' if len(sans) > 8 else '')\n",
            "\n",
            "player_selection = select_analyzed_player(\n",
            "    normalized_game,\n",
            "    username=PLAYER_NAME or None,\n",
            "    color=PLAYER_COLOR,\n",
            ")\n",
            "print(\n",
            "    f'Jugador analizado: {player_selection.username} '\n",
            "    f'({player_selection.color}) — {player_selection.move_count} jugadas'\n",
            ")\n",
            "print('SAN del jugador:', ' '.join(p.san for p in player_selection.plies))\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 2 — Reconstruir tablero hasta el ply elegido\n",
            "\n",
            "Tras la jugada del rival, **tú** tienes que decidir → evaluamos `fen_before` de esa jugada.\n",
            "\n",
            "Fijá **`TARGET_PLY`** o **`TARGET_MOVE_NUMBER`** en esta celda y volvé a ejecutarla. Tablero interactivo (Chessground), no SVG.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "print(f'Plies en la partida: 0 … {len(normalized_game.plies) - 1}')\n",
            "print('Tus decisiones (ply | #jugada | SAN) — usá estos ply en TARGET_PLY:')\n",
            "for rec in player_selection.plies:\n",
            "    print(f'  {rec.ply:4d} | {rec.move_number:3d} | {rec.san}')\n",
            "\n",
            "# --- fijar el momento (cambiar y re-ejecutar ESTA celda) ---\n",
            "TARGET_PLY = None            # ej. 12  (índice de la lista de arriba)\n",
            "TARGET_MOVE_NUMBER = None    # ej. 17  (jugada 17 tuya; manda sobre TARGET_PLY)\n",
            "\n",
            "if TARGET_MOVE_NUMBER is not None:\n",
            "    matches = [r for r in player_selection.plies if r.move_number == int(TARGET_MOVE_NUMBER)]\n",
            "    if not matches:\n",
            "        raise ValueError(\n",
            "            f'TARGET_MOVE_NUMBER={TARGET_MOVE_NUMBER} no es una jugada de '\n",
            "            f'{player_selection.username} ({player_selection.color})'\n",
            "        )\n",
            "    record = matches[0]\n",
            "    ply = record.ply\n",
            "elif TARGET_PLY is not None:\n",
            "    ply = int(TARGET_PLY)\n",
            "    if ply < 0 or ply >= len(normalized_game.plies):\n",
            "        raise ValueError(\n",
            "            f'TARGET_PLY={ply} fuera de rango (0 … {len(normalized_game.plies) - 1})'\n",
            "        )\n",
            "    record = normalized_game.plies[ply]\n",
            "    if record.side_to_move != player_selection.color:\n",
            "        print(\n",
            "            f'AVISO: ply {ply} es de {record.side_to_move}, no de '\n",
            "            f'{player_selection.color}. Elegí un ply de la lista de arriba.'\n",
            "        )\n",
            "else:\n",
            "    record = player_selection.plies[-1]\n",
            "    ply = record.ply\n",
            "    print('TARGET_PLY/TARGET_MOVE_NUMBER vacíos → última decisión del jugador.')\n",
            "\n",
            "board = chess.Board(record.fen_before)\n",
            "side = 'Blancas' if record.side_to_move == 'white' else 'Negras'\n",
            "print()\n",
            "print(f'Ply {ply} | jugada {record.move_number} | a mover: {side}')\n",
            "print(f'Jugada que se eligió en la partida: {record.san} ({record.uci})')\n",
            "print('FEN (posición a decidir, antes de esa jugada):', board.fen())\n",
            "lastmove = None\n",
            "if record.ply > 0:\n",
            "    lastmove = normalized_game.plies[record.ply - 1].uci\n",
            "show_interactive_board(\n",
            "    board,\n",
            "    lastmove=lastmove,\n",
            "    orientation=player_selection.color,\n",
            "    view_only=False,\n",
            ")\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 3 — Stockfish hasta review pack (F07-003–006, F07-012–016, F07-019, F07-028, F07-035)\n",
            "\n",
            "Evalúa el ply, MultiPV, comparación y abstención. F07-035 exporta un JSON (FEN, PGN, candidatas, evidencia) a `artifacts/module07/`.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "score_before = None\n",
            "score_after = None\n",
            "\n",
            "if stockfish_available():\n",
            "    ply_eval = analyze_ply_for_player(\n",
            "        record.fen_before,\n",
            "        record.uci,\n",
            "        player_selection.color,\n",
            "        depth=12,\n",
            "    )\n",
            "    print(f'Stockfish depth {ply_eval.analysis.depth} ({ply_eval.analysis.engine_name})')\n",
            "    print('White-POV antes/después:', ply_eval.analysis.eval_before, ply_eval.analysis.eval_after)\n",
            "    print(f'Jugador {ply_eval.player_color} antes:', ply_eval.before)\n",
            "    print(f'Jugador {ply_eval.player_color} después:', ply_eval.after)\n",
            "    loss = ply_evaluation_loss(ply_eval)\n",
            "    drop = ply_evaluation_drop(ply_eval)\n",
            "    crit = assess_ply_criticality(record, ply_eval)\n",
            "    print(f'eval_delta: {loss.eval_delta} | eval_loss/cp_loss: {loss.eval_loss}')\n",
            "    print(f'{drop.code} fired={drop.fired} (threshold {drop.threshold_cp} cp)')\n",
            "    print(f'criticality {crit.score} {crit.level} critical={crit.critical}')\n",
            "    SCORE_ALL_PLAYER_PLIES = False\n",
            "    if SCORE_ALL_PLAYER_PLIES:\n",
            "        print('--- top 5 (F07-013; excluye Routine) ---')\n",
            "        ranked = rank_player_game(player_selection, depth=12, top_n=5)\n",
            "        if not ranked:\n",
            "            print('  (ningún ply ≥ Relevant)')\n",
            "        for row in ranked:\n",
            "            item = row.item\n",
            "            print(\n",
            "                f'  #{row.rank} ply {item.ply:4d} {item.san:8s} '\n",
            "                f'{item.score:4.1f} {item.level}'\n",
            "            )\n",
            "    print('--- MultiPV 3 (F07-014) ---')\n",
            "    mpv = analyze_multipv(\n",
            "        record.fen_before,\n",
            "        depth=12,\n",
            "        multipv=3,\n",
            "        player_color=player_selection.color,\n",
            "    )\n",
            "    for line in mpv.lines:\n",
            "        pv = ' '.join(line.pv_san[:6])\n",
            "        print(\n",
            "            f'  #{line.multipv_rank} {line.move_san:8s} '\n",
            "            f'{line.player_score}  pv: {pv}'\n",
            "        )\n",
            "    only = only_move_trigger(mpv, fen=record.fen_before)\n",
            "    print(f'{only.code} fired={only.fired} gap={only.eval_loss} (threshold {only.threshold_cp} cp)')\n",
            "    played = evaluate_played_move(\n",
            "        record.fen_before,\n",
            "        record.uci,\n",
            "        depth=12,\n",
            "        multipv=3,\n",
            "        player_color=player_selection.color,\n",
            "        multipv_result=mpv,\n",
            "    )\n",
            "    if played.in_multipv:\n",
            "        print(f'Jugada jugada {played.move_san}: MultiPV #{played.multipv_rank}')\n",
            "    else:\n",
            "        print(f'Jugada jugada {played.move_san}: no está en MultiPV ({played.source})')\n",
            "    print('  eval jugador:', played.player_score)\n",
            "    print(\n",
            "        f'notación F07-016: {record.uci} → {uci_to_san(record.fen_before, record.uci)}'\n",
            "        f' → {san_to_uci(record.fen_before, record.san)}'\n",
            "    )\n",
            "    vs = compare_played_to_candidates(\n",
            "        record.fen_before,\n",
            "        record.uci,\n",
            "        depth=12,\n",
            "        multipv=3,\n",
            "        player_color=player_selection.color,\n",
            "        multipv_result=mpv,\n",
            "        played=played,\n",
            "    )\n",
            "    best_san = vs.best.move_san if vs.best else '-'\n",
            "    print('--- F07-019 jugada vs candidatas ---')\n",
            "    print(\n",
            "        f'  {vs.played.move_san} vs mejor {best_san}  '\n",
            "        f'gap={vs.eval_gap_vs_best_cp} cp  '\n",
            "        f'best={vs.played_is_best}  propósito {vs.played_purpose.value}'\n",
            "    )\n",
            "    print(\n",
            "        f'  consecuencia: tags={vs.played_consequence.tags} '\n",
            "        f'material_delta={vs.played_consequence.material_delta_cp}'\n",
            "    )\n",
            "    for row in vs.diffs:\n",
            "        pv = ' '.join(row.pv_san[:5])\n",
            "        print(\n",
            "            f'  #{row.candidate.multipv_rank} {row.candidate.move_san:8s} '\n",
            "            f'gap {row.eval_gap_cp:6d}  '\n",
            "            f'{row.purpose.value} differs={row.purpose_differs}  pv: {pv}'\n",
            "        )\n",
            "    gate = assess_diagnosis_abstention(vs)\n",
            "    print('--- F07-028 abstención ---')\n",
            "    print(f'  {gate.status} may_diagnose={gate.may_diagnose} reasons={gate.reasons}')\n",
            "    print(f'  {gate.message}')\n",
            "    pack = build_review_pack(\n",
            "        normalized_game,\n",
            "        record,\n",
            "        player_selection,\n",
            "        vs,\n",
            "        gate,\n",
            "        pgn_source=str(PGN_PATH) if not GAME_ID else f'sqlite:{GAME_ID}',\n",
            "        criticality=crit,\n",
            "        eval_loss=loss,\n",
            "    )\n",
            "    pack_path = ARTIFACT_DIR / default_review_pack_name(\n",
            "        normalized_game.game_id, record.ply, record.san\n",
            "    )\n",
            "    write_review_pack(pack, pack_path)\n",
            "    print('--- F07-035 review pack ---')\n",
            "    print('  saved:', pack_path)\n",
            "    print('  status:', pack['status'], '| candidates:', len(pack['candidates']))\n",
            "else:\n",
            "    print('STOCKFISH_PATH no encontrado; se omite F07-003–006/012–016/019/028/035 en vivo.')\n",
            "    print(\n",
            "        f'notación F07-016: {record.uci} → {uci_to_san(record.fen_before, record.uci)}'\n",
            "    )\n",
            "    ply_eval = None\n",
            "\n",
            "if normalized_game.source == 'database' and ply > 0:\n",
            "    prev = normalized_game.plies[ply - 1]\n",
            "    curr = normalized_game.plies[ply]\n",
            "    score_before = prev.score_diff\n",
            "    score_after = curr.score_diff\n",
            "    print('score_diff desde features SQLite:')\n",
            "else:\n",
            "    print('Sin score_diff automático (PGN local). Edita manualmente si lo conoces.')\n",
            "\n",
            "# Override manual opcional\n",
            "# score_before = 20\n",
            "# score_after = -60\n",
            "print('score_before:', score_before, '| score_after:', score_after)\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 4 — Evaluar: ¿modo rápido (C/C1) o crítico (E→F→G→…)?\n",
            "\n",
            "Corresponde al diagrama [`algoritmo_posiciones_criticas_ajedrez.html`](./07_cc_detection_algoritms/algoritmo_posiciones_criticas_ajedrez.html).\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "assessment = assess_decision_point(\n",
            "    board=board.copy(),\n",
            "    time_control=TIME_CONTROL,\n",
            "    player_elo=PLAYER_ELO,\n",
            "    score_diff_before=score_before,\n",
            "    score_diff_after=score_after,\n",
            ")\n",
            "\n",
            "print('=== MODO ===')\n",
            "print(assessment.mode.value.upper())\n",
            "print('Pausa sugerida (s):', assessment.pause_seconds)\n",
            "\n",
            "print('\\n=== DISPARADORES E1–E11 ===')\n",
            "if not assessment.triggers:\n",
            "    print('(ninguno — coherente con modo rápido C/C1)')\n",
            "for t in assessment.triggers:\n",
            "    print(f\"  {t.code.value} [{t.confidence:.2f}] {t.label_es}\")\n",
            "    for ev in t.evidence:\n",
            "        print(f'      - {ev}')\n",
            "\n",
            "print('\\n=== MAPEO 07-base (CriticalityReason) ===')\n",
            "print(assessment.mapped_07_reasons or ['(ninguno)'])\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 5 — Plan de pensamiento (pasos del HTML)\n",
            "\n",
            "Usa `assessment` de Paso 4. Si saltaste esa celda, se calcula acá.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "if 'assessment' not in globals() or assessment is None:\n",
            "    if 'board' not in globals():\n",
            "        raise RuntimeError('Corré Paso 2 y Paso 4 antes (falta board/assessment).')\n",
            "    assessment = assess_decision_point(\n",
            "        board=board.copy(),\n",
            "        time_control=TIME_CONTROL,\n",
            "        player_elo=PLAYER_ELO,\n",
            "        score_diff_before=globals().get('score_before'),\n",
            "        score_diff_after=globals().get('score_after'),\n",
            "    )\n",
            "    print('assessment no estaba definido: se calculó ahora. Corré Paso 4 para ver modo y disparadores.')\n",
            "\n",
            "plan_df = pd.DataFrame(\n",
            "    [\n",
            "        {'nodo': s.node_id, 'fase': s.phase, 'pregunta': s.prompt_es}\n",
            "        for s in assessment.thinking_plan\n",
            "    ]\n",
            ")\n",
            "plan_df\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 6 — Generar candidatas (D1–D5) desde jugadas legales\n",
            "\n",
            "En producción esto se alimentará con Stockfish MultiPV. Aquí clasificamos las legales con la heurística del HTML candidatas.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "position = board.copy()\n",
            "legal = list(position.legal_moves)\n",
            "ordered = sort_candidates_by_priority(position, legal[:12])  # limitar para display\n",
            "\n",
            "rows = []\n",
            "for move, cat in ordered[:8]:\n",
            "    rows.append({\n",
            "        'uci': move.uci(),\n",
            "        'san': position.san(move),\n",
            "        'categoria': cat.value,\n",
            "    })\n",
            "candidates_df = pd.DataFrame(rows)\n",
            "print('Top candidatas heurísticas (orden F: forzante → activa → sólida):')\n",
            "candidates_df\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 7 — Anti-blunder (S1–S4) sobre una candidata\n",
            "\n",
            "Edita `CANDIDATE_UCI` en Paso 0, o usa la primera de la tabla.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "uci = CANDIDATE_UCI or (candidates_df.iloc[0]['uci'] if len(candidates_df) else None)\n",
            "if uci is None:\n",
            "    print('Sin candidata para probar.')\n",
            "else:\n",
            "    move = chess.Move.from_uci(uci)\n",
            "    move_assessment = assess_move_before_play(\n",
            "        board.copy(), move,\n",
            "        time_control=TIME_CONTROL,\n",
            "        player_elo=PLAYER_ELO,\n",
            "        score_diff_before=score_before,\n",
            "        score_diff_after=score_after,\n",
            "    )\n",
            "    print('Candidata:', uci, '→', board.san(move) if move in board.legal_moves else '(ilegal)')\n",
            "    print('¿Pasa anti-blunder?', move_assessment.meta.get('move_safe'))\n",
            "    print('Checks fallidos:', move_assessment.meta.get('anti_blunder_failed', []))\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 8 — Recorrer toda la partida (momentos notables)\n",
            "\n",
            "`critical` ya no es “cualquier E1–E11”. Solo: cambio de piezas, estructura de peones, cómo retomar (peón/dama/gambito), centro, o lío táctico (jaque, torre/dama colgando, dama a b2/b7). Los E quedan como atención, no definen el modo.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "summary_rows = []\n",
            "for record in player_selection.plies:\n",
            "    prev_score = normalized_game.plies[record.ply - 1].score_diff if record.ply > 0 else None\n",
            "    if record.ply > 0:\n",
            "        prev = normalized_game.plies[record.ply - 1]\n",
            "        a = assess_decision_point(\n",
            "            board=chess.Board(prev.fen_before),\n",
            "            last_move_uci=prev.uci,\n",
            "            time_control=TIME_CONTROL,\n",
            "            player_elo=PLAYER_ELO,\n",
            "            score_diff_before=prev_score,\n",
            "            score_diff_after=record.score_diff,\n",
            "        )\n",
            "    else:\n",
            "        a = assess_decision_point(\n",
            "            board=chess.Board(record.fen_before),\n",
            "            time_control=TIME_CONTROL,\n",
            "            player_elo=PLAYER_ELO,\n",
            "        )\n",
            "    notable = ','.join(r.kind.value for r in a.notable_reasons) or '-'\n",
            "    summary_rows.append({\n",
            "        'ply': record.ply,\n",
            "        'san_before': record.san,\n",
            "        'mode': a.mode.value,\n",
            "        'notable': notable,\n",
            "        'attention_E': ','.join(t.code.value for t in a.triggers) or '-',\n",
            "        'pause_s': a.pause_seconds,\n",
            "    })\n",
            "\n",
            "summary_df = pd.DataFrame(summary_rows)\n",
            "print(f'Plies del jugador {player_selection.username} ({player_selection.color}): {len(summary_df)}')\n",
            "print('Críticos notables:', (summary_df['mode'] == 'critical').sum())\n",
            "summary_df\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Paso 9 — Exportar resultado JSON\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "outputs": [],
        "execution_count": None,
        "source": [
            "if 'assessment' not in globals() or assessment is None:\n",
            "    raise RuntimeError('Corré Paso 4 (evaluación) antes de exportar.')\n",
            "\n",
            "export = {\n",
            "    'game_id': normalized_game.game_id,\n",
            "    'source': normalized_game.source,\n",
            "    'fen': assessment.meta.get('fen'),\n",
            "    'mode': assessment.mode.value,\n",
            "    'pause_seconds': assessment.pause_seconds,\n",
            "    'notable_reasons': [\n",
            "        {'kind': r.kind.value, 'evidence': r.evidence}\n",
            "        for r in assessment.notable_reasons\n",
            "    ],\n",
            "    'triggers': [\n",
            "        {'code': t.code.value, 'label': t.label_es, 'evidence': t.evidence}\n",
            "        for t in assessment.triggers\n",
            "    ],\n",
            "    'mapped_07_reasons': assessment.mapped_07_reasons,\n",
            "    'thinking_plan': [\n",
            "        {'node': s.node_id, 'phase': s.phase, 'prompt': s.prompt_es}\n",
            "        for s in assessment.thinking_plan\n",
            "    ],\n",
            "}\n",
            "out_path = ARTIFACT_DIR / 'mental_model_assessment.json'\n",
            "out_path.write_text(json.dumps(export, ensure_ascii=False, indent=2), encoding='utf-8')\n",
            "print('Guardado:', out_path)\n",
        ],
    },
]

nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "pygments_lexer": "ipython3"},
    },
    "cells": cells,
}

out = Path(__file__).resolve().parent / "07_0_mental_model_lab.ipynb"
out.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding="utf-8")
print(f"Wrote {out}")
