"""initial_database_schema

Revision ID: 0b916c932d3b
Revises: 
Create Date: 2025-08-23 23:44:36.915608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b916c932d3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzed_tacticals',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('date_analyzed', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('game_id'),
    schema='public'
    )
    op.create_table('features',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('player_color', sa.Integer(), nullable=False),
    sa.Column('fen', sa.String(), nullable=True),
    sa.Column('move_san', sa.String(), nullable=True),
    sa.Column('move_uci', sa.String(), nullable=True),
    sa.Column('error_label', sa.String(), nullable=True),
    sa.Column('material_balance', sa.Float(), nullable=True),
    sa.Column('material_total', sa.Float(), nullable=True),
    sa.Column('num_pieces', sa.Integer(), nullable=True),
    sa.Column('branching_factor', sa.Integer(), nullable=True),
    sa.Column('self_mobility', sa.Integer(), nullable=True),
    sa.Column('opponent_mobility', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('has_castling_rights', sa.Integer(), nullable=True),
    sa.Column('move_number_global', sa.Integer(), nullable=True),
    sa.Column('is_repetition', sa.Integer(), nullable=True),
    sa.Column('is_low_mobility', sa.Integer(), nullable=True),
    sa.Column('is_center_controlled', sa.Integer(), nullable=True),
    sa.Column('is_pawn_endgame', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('score_diff', sa.Float(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('white_player', sa.String(), nullable=True),
    sa.Column('black_player', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('num_moves', sa.Integer(), nullable=True),
    sa.Column('is_stockfish_test', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('game_id', 'move_number', 'player_color'),
    schema='public'
    )
    op.create_table('games',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('pgn', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('white_player', sa.String(), nullable=True),
    sa.Column('black_player', sa.String(), nullable=True),
    sa.Column('white_elo', sa.String(), nullable=True),
    sa.Column('black_elo', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('time_control', sa.String(), nullable=True),
    sa.Column('opening', sa.String(), nullable=True),
    sa.Column('eco', sa.String(), nullable=True),
    sa.Column('date_played', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('game_id'),
    schema='public'
    )
    op.create_table('studies',
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('study_id'),
    schema='public'
    )
    op.create_table('study_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=True),
    sa.Column('fen', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('is_critical', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_positions', schema='public')
    op.drop_table('studies', schema='public')
    op.drop_table('games', schema='public')
    op.drop_table('features', schema='public')
    op.drop_table('analyzed_tacticals', schema='public')
    # ### end Alembic commands ###
